/**
 * Created by NTS-HP-PC on 23/10/2018.
 */
var router = require('express').Router();

var seviceRoute = require('./service');
var specialiteRoute = require('./specialite');
var uniteRoute = require('./unite');
var equipementRoute = require('./equipement');
var chambreRoute = require('./chambre');
var litRoute = require('./lit');
var pathologieRoute = require('./pathologie');
var trvsRoute = require('./typervs');
var tconsultRoute = require('./typeconsult');
var texamenRoute = require('./typeexamen');
var bmedicamentRoute = require('./basemedicament');
var diagnostiqueRoute = require('./basediagnostique');
var privilegeRoute = require('./privilege');
var pprivilegeRoute = require('./pprivilege');
var uprivilegeRoute = require('./uprivilege');
var cequipementRoute = require('./cequipement');
var profilgeRoute = require('./profil');
var fpharmaceutiqueRoute = require('./fpharmaceutique');
var vadministrationRoute = require('./vadministration');
var phlaboRoute = require('./phlabo');
var telementRoute = require('./telement');
var titreRoute = require('./titre');
var personneRoute = require('./personne');
var medecinRoute = require('./medecin');
var infirmierRoute = require('./infirmier');
var adpersonnelRoute = require('./adpersonnel');
var utilisateurRoute = require('./utilisateur');
var tlicenceRoute = require('./tlicence');
var licenceRoute = require('./licence');
var menuRoute = require('./menu');
var smenuRoute = require('./smenu');
var rhesusRoute = require('./rhesus');
var gsanguinRoute = require('./gsanguin');
var patientRoute = require('./patient');
var cmotifRoute = require('./cmotif');
var mconsultationRoute = require('./mconsultation');
var tconstanteRoute = require('./tconstante');
var releveRoute = require('./releve');
var consultationRoute = require('./consultation');
var ordonnanceRoute = require('./ordonnance');
var ctransfertRoute = require('./ctransfert');
var rdvRoute = require('./rdv');
var oligneRoute = require('./oligne');
var fileRoute = require('./file');


router.use('/service', seviceRoute);
router.use('/specialite', specialiteRoute);
router.use('/unite', uniteRoute);
router.use('/equipement', equipementRoute);
router.use('/chambre', chambreRoute);
router.use('/lit', litRoute);
router.use('/pathologie', pathologieRoute);
router.use('/trvs', trvsRoute);
router.use('/tconsult', tconsultRoute);
router.use('/texamen', texamenRoute);
router.use('/bmedicament', bmedicamentRoute);
router.use('/basediagnostique', diagnostiqueRoute);
router.use('/privilege', privilegeRoute);
router.use('/pprivilege', pprivilegeRoute);
router.use('/uprivilege', uprivilegeRoute);
router.use('/cequipement', cequipementRoute);
router.use('/profil', profilgeRoute);
router.use('/fpharmaceutique', fpharmaceutiqueRoute);
router.use('/vadministration', vadministrationRoute);
router.use('/phlabo', phlaboRoute);
router.use('/telement', telementRoute);
router.use('/titre', titreRoute);
router.use('/personne', personneRoute);
router.use('/medecin', medecinRoute);
router.use('/infirmier', infirmierRoute);
router.use('/adpersonnel', adpersonnelRoute);
router.use('/utilisateur', utilisateurRoute);
router.use('/licence', licenceRoute);
router.use('/tlicence', tlicenceRoute);
router.use('/menu', menuRoute);
router.use('/smenu', smenuRoute);
router.use('/rhesus', rhesusRoute);
router.use('/gsanguin', gsanguinRoute);
router.use('/patient', patientRoute);
router.use('/cmotif', cmotifRoute);
router.use('/mconsultation', mconsultationRoute);
router.use('/tconstante', tconstanteRoute);
router.use('/releve', releveRoute);
router.use('/consultation', consultationRoute);
router.use('/ordonnance', ordonnanceRoute);
router.use('/ctransfert', ctransfertRoute);
router.use('/oligne', oligneRoute);
router.use('/rdv', rdvRoute);
router.use('/file', fileRoute);

module.exports = router;